
PATH_CUTNRUN=../cutandrun_20240313_nodupes
FILES_CUTNRUN= pos_saos2_DN_R1.clipped.clean.bed pos_saos2_GFP_R1.clipped.clean.bed pos_saos2_TA_R1.clipped.clean.bed \
pos_skmel29_2_DN_R1.clipped.clean.bed pos_skmel29_2_GFP_R1.clipped.clean.bed pos_skmel29_2_TA_R1.clipped.clean.bed \
tp73_saos2_DN_R1.clipped.clean.bed tp73_saos2_GFP_R1.clipped.clean.bed tp73_saos2_TA_R1.clipped.clean.bed \
tp73_skmel29_2_DN_R1.clipped.clean.bed tp73_skmel29_2_GFP_R1.clipped.clean.bed tp73_skmel29_2_TA_R1.clipped.clean.bed

REST_MA0138.2_negative_1.bed REST_MA0138.2_positive_1.bed:

SP1_MA0079.5_negative_1.bed SP1_MA0079.5_positive_1.bed:

TP73_MA0861.1_negative_1.bed TP73_MA0861.1_positive_1.bed:

# Define target dependencies explicitly if needed
all: TP73_MA0861.1_positive_1.combined.bed REST_MA0138.2_positive_1.combined.bed SP1_MA0079.5_positive_1.combined.bed 

# Rule to generate combined.bed files from bed files representing PSSM mapping
%.combined.bed: %.bed.gz $(FILES_CUTNRUN)
	
	#for i in $(FILES_CUTNRUN); do \
	#	$(MAKE) $$i ; \
	#done
	#rm -f a.bed
	
	zcat $< > a.bed
	
	echo -n "Chr\tFrom\tTo\tName\tScore\tStrand" > $*.combined.bed
	for i in $(FILES_CUTNRUN); do \
		echo "I: Working on $$i" ; \
		echo -n "\t" >> $*.combined.bed ; \
		echo -n $$i | sed -e 's/_R1.clipped.clean.bed$$//' >> $*.combined.bed ; \
		if [ -f a.bed ]; then \
			bedtools map -null 0 -a a.bed -b $$i > b.bed; \
			mv b.bed a.bed; \
		else \
	        echo "E: a.bed should be existing" ; \
	        exit ; \
		fi ; \
	done
	echo >> $*.combined.bed
	
	cat a.bed >> $*.combined.bed
	#rm a.bed

# Rule to generate clean.bed files from bedGraph files in PATH_CUTNRUN
%.clean.bed: $(PATH_CUTNRUN)/%.bedGraph
	grep -v hromosome $(PATH_CUTNRUN)/$*.bedGraph | sed -e 's%^chr%%' |awk '{print $$1"\t"$$2"\t"$$3"\tcnr\t"$$4}' > $*.clean.bed

.SUFFIXES: .bed .bedGraph .combined.bed,
