#!/bin/bash -e

if [ ! -d "scripts" ]; then
        echo "E: Execute the script from the root of the Jaspar folder"
        exit 1
fi

ofolder="GeneLists"
mkdir -p "$ofolder"

URL_prefix="https://www.gsea-msigdb.org/gsea/msigdb/human/download_geneset.jsp?geneSetName="
URL_postfix="&fileType=TSV"
lists="REACTOME_TP53_REGULATES_TRANSCRIPTION_OF_CELL_CYCLE_GENES REACTOME_TP53_REGULATES_TRANSCRIPTION_OF_CELL_DEATH_GENES REACTOME_TP53_REGULATES_TRANSCRIPTION_OF_DEATH_RECEPTORS_AND_LIGANDS REACTOME_TP53_REGULATES_TRANSCRIPTION_OF_GENES_INVOLVED_IN_G1_CELL_CYCLE_ARREST REACTOME_TP53_REGULATES_TRANSCRIPTION_OF_GENES_INVOLVED_IN_G2_CELL_CYCLE_ARREST REACTOME_TRANSCRIPTIONAL_REGULATION_BY_TP53 TANG_SENESCENCE_TP53_TARGETS_DN TANG_SENESCENCE_TP53_TARGETS_UP WP_MIRNA_REGULATION_OF_P53_PATHWAY_IN_PROSTATE_CANCER WP_P53_TRANSCRIPTIONAL_GENE_NETWORK WP_TP53_NETWORK REACTOME_TRANSCRIPTIONAL_REGULATION_BY_TP53 REACTOME_INTRINSIC_PATHWAY_FOR_APOPTOSIS REACTOME_REGULATION_OF_APOPTOSIS REACTOME_REGULATION_OF_MITF_M_DEPENDENT_GENES_INVOLVED_IN_APOPTOSIS REACTOME_SUPPRESSION_OF_APOPTOSIS REACTOME_TP53_REGULATES_TRANSCRIPTION_OF_SEVERAL_ADDITIONAL_CELL_DEATH_GENES_WHOSE_SPECIFIC_ROLES_IN_P53_DEPENDENT_APOPTOSIS_REMAIN_UNCERTAIN WP_APOPTOSIS_MODULATION_AND_SIGNALING WP_APOPTOSIS_MODULATION_BY_HSP70 WP_QUERCETIN_AND_NFKB_AP1_INDUCED_APOPTOSIS REACTOME_APOPTOSIS REACTOME_APOPTOSIS_INDUCED_DNA_FRAGMENTATION REACTOME_DEFECTIVE_INTRINSIC_PATHWAY_FOR_APOPTOSIS REACTOME_EXTRINSIC_PATHWAY_FOR_APOPTOSIS WP_APOPTOSIS KEGG_APOPTOSIS LIN_MELANOMA_COPY_NUMBER_DN LIN_MELANOMA_COPY_NUMBER_UP NABA_MATRISOME_HIGHLY_METASTATIC_MELANOMA NABA_MATRISOME_HIGHLY_METASTATIC_MELANOMA_TUMOR_CELL_DERIVED NABA_MATRISOME_POORLY_METASTATIC_MELANOMA NABA_MATRISOME_POORLY_METASTATIC_MELANOMA_TUMOR_CELL_DERIVED ONKEN_UVEAL_MELANOMA_DN ONKEN_UVEAL_MELANOMA_UP WINNEPENNINCKX_MELANOMA_METASTASIS_DN WINNEPENNINCKX_MELANOMA_METASTASIS_UP WP_INHIBITION_OF_GNAQREGULATED_SIGNALING_IN_UVEAL_MELANOMA WP_MELANOMA HP_MELANOMA JIANG_MELANOMA_TRM_HIGH_SURVIVAL_22_GENE_SIGNATURE KAUFFMANN_MELANOMA_RELAPSE_DN KAUFFMANN_MELANOMA_RELAPSE_UP JIANG_MELANOMA_TRM_HIGH_SURVIVAL_22_GENE_SIGNATURE WP_HALLMARK_OF_CANCER_NONMUTATIONAL_EPIGENETIC_REPROGRAMMING HALLMARK_IL6_JAK_STAT3_SIGNALING HALLMARK_HYPOXIA HALLMARK_E2F_TARGETS WP_HALLMARK_OF_CANCER_METASTASIS_AND_EPITHELIALTOMESENCHYMAL_TRANSITION WP_HALLMARK_OF_CANCER_SUSTAINING_PROLIFERATIVE_SIGNALING HALLMARK_INTERFERON_GAMMA_RESPONSE HALLMARK_INTERFERON_ALPHA_RESPONSE HALLMARK_PI3K_AKT_MTOR_SIGNALING HALLMARK_TGF_BETA_SIGNALING HALLMARK_ANGIOGENESIS HALLMARK_APOPTOSIS HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION HALLMARK_INFLAMMATORY_RESPONSE HALLMARK_P53_PATHWAY HALLMARK_WNT_BETA_CATENIN_SIGNALING KEGG_MELANOMA REACTOME_NEURONAL_SYSTEM Nico_Analysis_DN_20250508 Nico_Analysis_DN_20250618 Nico_Analysis_DN_Methup_20250618 Nico_Analysis_TA_20250508 Nico_Analysis_TA_20250618 Nico_Analysis_TAandDN_20250508 Nico_Analysis_TA_MethUp_20250618"

for list in $lists; do
    echo "$list"

    fname="$ofolder/$list.tsv"
    if [ -f "$fname" ]; then
        echo "I: $fname already exists - skipping download"
    else
        URL="$URL_prefix$list$URL_postfix"
        echo "$URL"
        echo "I: Downloading $list to $fname"
        wget -O "$fname" "$URL"
    fi
    if [ -f "$ofolder/$list.promoter.bed" ] && [ -f "$ofolder/$list.transcript.bed" ]&& [ -f "$ofolder/$list.utr.bed" ]; then
        echo "I: $list.promoter.bed and $list.transcript.bed already exist - skipping"
        continue
    else
        #echo "D: Grepping genes"
        if ! genes=$(grep GENE_SYMBOLS "$fname" | cut -f2 | grep -v "^GENE_SYMBOL"); then
            echo "E: Could not grep for GENE_SYMBOLS, check if a true tab is separating the genes from the row name."
            exit 1
        fi
        #echo "D: Grepping genes found $genes"
        ./gtf_file_region_retrieval -c 1 -n "$genes" -f promoter > "$ofolder/$list.promoter.bed"
        ./gtf_file_region_retrieval -c 1 -n "$genes" -f utr > "$ofolder/$list.utr.bed"
        ./gtf_file_region_retrieval -c 1 -n "$genes" > "$ofolder/$list.transcript.bed"
    fi
done
